services:
  - type: web
    name: mediqura-django-backend
    runtime: python3
    rootDir: mediqura-django
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

  - type: web
    name: mediqura-react-frontend
    runtime: node
    rootDir: medqura-frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://mediqura-django-backend.onrender.com/api